openapi: 3.0.3
info:
  contact:
    email: giacomo.cortesi1993@gmail.com
  description: AI Music to Subtitles API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AI Music Subtitles - OpenAPI 3.0
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://localhost:8000
tags:
- description: Music AI subtitles generator jobs
  name: job
- description: Transcription CRUD operations
  name: transcription
- description: Video files CRUD operations
  name: video
paths:
  /job:
    get:
      operationId: job_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/JobResponse'
                type: array
          description: Jobs details successfully retrieved
      summary: Get all job details
      tags:
      - job
      x-openapi-router-controller: openapi_server.controllers.job_controller
    post:
      operationId: job_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
          description: Subtitles generation job successfully created
      summary: Create a new subtitles generation job
      tags:
      - job
      x-openapi-router-controller: openapi_server.controllers.job_controller
  /job/{job_id}:
    get:
      operationId: job_job_id_get
      parameters:
      - explode: false
        in: path
        name: job_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
          description: Job details successfully retrieved
      summary: Get job details
      tags:
      - job
      x-openapi-router-controller: openapi_server.controllers.job_controller
  /transcription:
    get:
      operationId: transcription_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Transcription'
                type: array
          description: A successful response
      summary: Fetch all transcriptions
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
    post:
      operationId: transcription_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_transcription_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transcription'
          description: A successful response
      summary: Creates a new transcription
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
  /transcription/{transcription_id}:
    delete:
      operationId: transcription_transcription_id_delete
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: A successful response
      summary: Deletes a specific transcription
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
    get:
      operationId: transcription_transcription_id_get
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transcription'
          description: A successful response
      summary: Retrieves a specific transcription
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
    patch:
      operationId: transcription_transcription_id_patch
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_transcription__transcription_id__patch_request'
        required: true
      responses:
        "204":
          description: A successful response
      summary: Edit a specific transcription
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
  /transcription/{transcription_id}/clear:
    post:
      operationId: transcription_transcription_id_clear_post
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: A successful response
      summary: Restores initial transcription
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
  /transcription/{transcription_id}/export:
    get:
      operationId: transcription_transcription_id_export_get
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      - description: The format to export the transcription in
        explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - srt
          - stt
          type: string
        style: deepObject
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: Successful export
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_transcription__transcription_id__export_get_400_response'
          description: Unsupported format
      summary: Export transcription in several subtitle formats
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
  /transcription/{transcription_id}/fit:
    post:
      operationId: transcription_transcription_id_fit_post
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: A successful response
      summary: Fit start and end of each subtitles segment
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
  /transcription/{transcription_id}/fix:
    post:
      operationId: transcription_transcription_id_fix_post
      parameters:
      - explode: false
        in: path
        name: transcription_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: A successful response
      summary: Attempts to fix all subtitles text with AI
      tags:
      - transcription
      x-openapi-router-controller: openapi_server.controllers.transcription_controller
  /video:
    delete:
      operationId: video_delete
      parameters:
      - description: "Filename of the video to be deleted, if no filename, all uploaded\
          \ videos are deleted"
        explode: true
        in: query
        name: filename
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          description: A successful response
      summary: Delete uploaded video file(s)
      tags:
      - video
      x-openapi-router-controller: openapi_server.controllers.video_controller
    get:
      operationId: video_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_video_get_200_response_inner'
                type: array
          description: A successful response
      summary: Retrieves the list of uploaded videos
      tags:
      - video
      x-openapi-router-controller: openapi_server.controllers.video_controller
    post:
      operationId: video_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_video_post_request'
        required: true
      responses:
        "200":
          description: A successful response
      summary: Uploads a video file
      tags:
      - video
      x-openapi-router-controller: openapi_server.controllers.video_controller
components:
  schemas:
    JobConfig:
      example:
        speaker_detection: true
        subtitles_frequency: 0
        hugging_face_token: hugging_face_token
        language: language
        model_size: model_size
      properties:
        model_size:
          title: model_size
          type: string
        subtitles_frequency:
          title: subtitles_frequency
          type: integer
        language:
          title: language
          type: string
        speaker_detection:
          title: speaker_detection
          type: boolean
        hugging_face_token:
          title: hugging_face_token
          type: string
      required:
      - hugging_face_token
      - language
      - model_size
      - speaker_detection
      - subtitles_frequency
      title: JobConfig
      type: object
    JobRequest:
      example:
        video_file: video_file
        config:
          speaker_detection: true
          subtitles_frequency: 0
          hugging_face_token: hugging_face_token
          language: language
          model_size: model_size
      properties:
        video_file:
          title: video_file
          type: string
        config:
          $ref: '#/components/schemas/JobConfig'
      required:
      - video_file
      title: JobRequest
      type: object
    JobResponse:
      example:
        data:
          language: language
          segments:
          - start: 6.0274563
            words:
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            end: 1.4658129
            text: text
          - start: 6.0274563
            words:
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            end: 1.4658129
            text: text
          word_segments:
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
        video_file: video_file
        config:
          speaker_detection: true
          subtitles_frequency: 0
          hugging_face_token: hugging_face_token
          language: language
          model_size: model_size
        status: pending
      properties:
        video_file:
          title: video_file
          type: string
        config:
          $ref: '#/components/schemas/JobConfig'
        status:
          enum:
          - pending
          - running
          - completed
          - failed
          title: status
          type: string
        data:
          $ref: '#/components/schemas/TranscriptionData'
      required:
      - config
      - status
      - transcription
      - video_file
      title: JobResponse
      type: object
    Word:
      example:
        score: 2.3021358869347655
        start: 5.962133916683182
        end: 5.637376656633329
        word: word
      properties:
        word:
          title: word
          type: string
        start:
          title: start
          type: number
        end:
          title: end
          type: number
        score:
          title: score
          type: number
      required:
      - end
      - score
      - start
      - word
      title: Word
      type: object
    Segment:
      example:
        start: 6.0274563
        words:
        - score: 2.3021358869347655
          start: 5.962133916683182
          end: 5.637376656633329
          word: word
        - score: 2.3021358869347655
          start: 5.962133916683182
          end: 5.637376656633329
          word: word
        end: 1.4658129
        text: text
      properties:
        start:
          format: float
          title: start
          type: number
        end:
          format: float
          title: end
          type: number
        text:
          title: text
          type: string
        words:
          items:
            $ref: '#/components/schemas/Word'
          title: words
          type: array
      required:
      - end
      - start
      - text
      title: Segment
      type: object
    Transcription:
      example:
        transcription_id: transcription_id
        data:
          language: language
          segments:
          - start: 6.0274563
            words:
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            end: 1.4658129
            text: text
          - start: 6.0274563
            words:
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            - score: 2.3021358869347655
              start: 5.962133916683182
              end: 5.637376656633329
              word: word
            end: 1.4658129
            text: text
          word_segments:
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
        job_id: job_id
        video_file: video_file
      properties:
        transcription_id:
          title: transcription_id
          type: string
        data:
          $ref: '#/components/schemas/TranscriptionData'
        job_id:
          title: job_id
          type: string
        video_file:
          title: video_file
          type: string
      title: Transcription
      type: object
    TranscriptionData:
      example:
        language: language
        segments:
        - start: 6.0274563
          words:
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
          end: 1.4658129
          text: text
        - start: 6.0274563
          words:
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
          - score: 2.3021358869347655
            start: 5.962133916683182
            end: 5.637376656633329
            word: word
          end: 1.4658129
          text: text
        word_segments:
        - score: 2.3021358869347655
          start: 5.962133916683182
          end: 5.637376656633329
          word: word
        - score: 2.3021358869347655
          start: 5.962133916683182
          end: 5.637376656633329
          word: word
      properties:
        segments:
          items:
            $ref: '#/components/schemas/Segment'
          title: segments
          type: array
        word_segments:
          items:
            $ref: '#/components/schemas/Word'
          title: word_segments
          type: array
        language:
          title: language
          type: string
      required:
      - segments
      title: TranscriptionData
      type: object
    _transcription_post_request:
      properties:
        data:
          $ref: '#/components/schemas/TranscriptionData'
        job_id:
          title: job_id
          type: string
      title: _transcription_post_request
      type: object
    _transcription__transcription_id__patch_request:
      properties:
        data:
          $ref: '#/components/schemas/TranscriptionData'
      title: _transcription__transcription_id__patch_request
      type: object
    _transcription__transcription_id__export_get_400_response:
      example:
        error: Unsupported format
      properties:
        error:
          example: Unsupported format
          title: error
          type: string
      title: _transcription__transcription_id__export_get_400_response
      type: object
    _video_get_200_response_inner:
      example:
        video_name: video_name
        video_id: video_id
        upload_date: 2000-01-23T04:56:07.000+00:00
      properties:
        video_id:
          title: video_id
          type: string
        video_name:
          title: video_name
          type: string
        upload_date:
          format: date-time
          title: upload_date
          type: string
      title: _video_get_200_response_inner
      type: object
    _video_post_request:
      properties:
        file:
          format: binary
          type: string
      type: object
